version: "3.9"

services:
  webserver:
    image: php:8.0-apache
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db
    volumes: 
      - ./src:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql
    restart: always
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOSTS: db
  
